import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: " H M Ali",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Ahsan",
      email: "aliashrafinfo05@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "A73",
      slug: "Samsung",
      category: "Samsung",
      image: "/images/p3.webp",
      price: 320,
      countInStock: 50,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      //_id: "2",
      name: "F21pro",
      slug: "OPPO",
      category: "OPPO",
      image: "/images/p1.webp",
      price: 40,
      countInStock: 50,
      brand: "OPPO",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      // _id: " 3",
      name: "Y53",
      slug: "VIVO",
      category: "VIVO",
      image: "/images/p4.webp",
      price: 750,
      countInStock: 50,
      brand: "VIVO",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      //_id: "4",
      name: "Camon18pro",
      slug: "INFINIX",
      category: "INFINIX",
      image: "/images/p2.webp",
      price: 200,
      countInStock: 50,
      brand: "INFINIX",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
  ],
};
export default data;
