const data = {
  products: [
    {
      _id: "1",
      name: "S4",
      slug: "Samsung",
      category: "Mobiles",
      image: "/images/pic1.png",
      price: 30000,
      countInStock: 10,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      _id: "2",
      name: "F9",
      slug: "OPPO",
      category: "Mobiles",
      image: "/images/f9.png",
      price: 40000,
      countInStock: 0,
      brand: "OPPO",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      _id: " 3",
      name: "FindX2",
      slug: "VIVO",
      category: "Mobiles",
      image: "/images/findx2.png",
      price: 120000,
      countInStock: 10,
      brand: "VIVO",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      _id: "4",
      name: "Find Mini",
      slug: "INFINIX",
      category: "Mobiles",
      image: "/images/img4.png",
      price: 80000,
      countInStock: 10,
      brand: "INFINIX",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
  ],
};
export default data;
