import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: " H M Ali",
      email: "welamehar777@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Ahsan",
      email: "aliashrafinfo05@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "S4",
      slug: "Samsung",
      category: "Samsung",
      image: "/images/pic1.png",
      price: 120,
      countInStock: 50,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      //_id: "2",
      name: "F9",
      slug: "OPPO",
      category: "OPPO",
      image: "/images/f9.png",
      price: 40,
      countInStock: 50,
      brand: "OPPO",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      // _id: " 3",
      name: "FindX2",
      slug: "VIVO",
      category: "VIVO",
      image: "/images/findx2.png",
      price: 750,
      countInStock: 50,
      brand: "VIVO",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
    {
      //_id: "4",
      name: "Find Mini",
      slug: "INFINIX",
      category: "INFINIX",
      image: "/images/img4.png",
      price: 200,
      countInStock: 50,
      brand: "INFINIX",
      rating: 4.5,
      numReviews: 10,
      description: "high quality phone",
    },
  ],
};
export default data;
